class Category(object):

    def __init__(self, id):
        self.id = id
        self.name = ""
        self.color = ""
        self.text_color = ""
        self.slug = ""
        self.topic_count = 0
        self.post_count = 0
        self.position = 0
        self.description = ""
        self.description_text = ""
        self.topic_url = ""
        self.logo_url = ""
        self.background_url = ""
        self.read_restricted = True
        self.permission = ""
        self.notification_level = ""
        self.can_edit = True
        self.topic_template = ""
        self.has_children = True
        self.available_groups = []
        self.auto_close_hours = 0
        self.auto_close_based_on_last_post = True
        self.group_permissions = []
        self.email_in = True
        self.email_in_allow_strangers = True
        self.suppress_from_homepage = True
        self.can_delete = True
        self.cannot_delete_reason = ""
        self.allow_badges = True
        self.custom_fields = {}
